version: "3"
services:
  nginx:
    ports:
      - "${NGINX_PORT}"

  website:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: npm start