version: "3"
services:
  nginx:
    image: nginx:alpine
    depends_on:
      - website
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  website:
    build: .
    environment:
      - PORT=${PORT}
      - MONGO_IP=${MONGO_IP}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
    depends_on:
      - mongoDB

  mongoDB:
    image: mongo:4.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: